---
- name: build list of workers
  debug:
    msg: "kube-worker-{{ item }}"
  loop: "{{ range(0, hetzner_worker_count)|list }}"
  register: workernames

- set_fact:
    workernames: "{{ workernames.results | map(attribute='msg') | list }}"

- set_fact: 
    kubemaster:
      - kube-master

- module_defaults:
    hcloud_server:
      api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type }}"
      datacenter: "{{ hetzner_datacenter }}"
      ssh_keys: "{{ hetzner_ssh_keys }}"
  block:
    - loop: "{{ kubemaster + workernames }}"
      hcloud_server:
        name: "{{ item }}"

- pause:
    seconds: 60

- name: Refresh inventory
  meta: refresh_inventory
